import Config

# Configure your database
# config :radio_beam, RadioBeam.Repo,
#   username: "postgres",
#   password: "postgres",
#   hostname: "localhost",
#   database: "radio_beam_dev",
#   stacktrace: true,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :radio_beam, RadioBeamWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  # clients will get confused with 200 the responses from debug_errors
  debug_errors: false,
  secret_key_base: "9ecAggd84rh0M/JB8+1W7mbwdheVluVOwRQsqI/Ov6zfGBF8FfCbZmKRH5HtUYu4",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:radio_beam, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:radio_beam, ~w(--watch)]}
  ]

config :radio_beam,
  server_name: "localhost",
  well_known_client: %{"m.homeserver" => %{"base_url" => "localhost:4000"}}

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :radio_beam, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
